<template>
  <div class="form-field-wrapper">
    <component
      v-if="field && field.meta && !field.meta.hidden"
      :key="field.field"
      :is="resolvedComponent"
      v-model="internalValue"
      :field="field.field"
      :width="field.meta?.width"
      :defaultValue="defaultValue"
      :label="label"
      :options="safeOptions"
      :required="required"
      :autoGenerated="internalAuto"
      :multiple="isMultiple"
      :collection="field.meta?.collection"
    />
    <span v-if="internalAuto" class="auto-badge">Auto‑generated</span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useDirectusField } from '../composables/useDirectusField'
import TextField from './fields/TextField.vue'
import RichTextField from './fields/RichTextField.vue'
import SelectField from './fields/SelectField.vue'
import DateField from './fields/DateField.vue'
import FileUploadField from './fields/FileUploadField.vue'
import BooleanInput from './fields/BooleanInput.vue'
import RelationSelect from './fields/RelationSelect.vue'

const fieldComponents: Record<string, any> = {
  TextField,
  RichTextField,
  SelectField,
  DateField,
  FileUploadField,
  BooleanInput,
  RelationSelect,
}

const props = defineProps<{ field: any; modelValue?: any }>()
const emit = defineEmits(['update:modelValue'])

// inject form context if parent provided it
const formContext = inject('directusForm', null)

const {
  internalValue,
  internalAuto,
  label,
  fieldLookup,
  required,
  safeOptions,
  defaultValue,
  isMultiple,
} = useDirectusField(props.field, props.modelValue, emit, formContext)

const resolvedComponent = computed(() => fieldComponents[fieldLookup.value] || TextField)
</script>

<style scoped>
.form-field-wrapper {
  margin-bottom: 1rem;
}
.auto-badge {
  font-size: 12px;
  padding: 4px 6px;
  border-radius: 4px;
  background: #eee;
  color: #333;
}
</style>
