services:
  mframework:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # make sure this directory has the same ownership as the mframework user from the Dockerfile
      # otherwise Elk will not be able to store configs for accounts
      # e.g., mkdir ./mframework-storage; sudo chown 911:911 ./mframework-storage
      - './mframework-storage:/mframework/data'
    ports:
      - 5314:5314
