[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_OPTIONS = '--max-old-space-size=4096'

# Redirect to Discord server
[[redirects]]
from = "https://chat.mframework.zone"
to = "https://discord.gg/vAZSDU9J"
status = 301
force = true

# Redirect to Discord server
[[redirects]]
from = "https://code.mframework.zone"
to = "https://github.com/mframework-zone/mframework"
status = 301
force = true
