<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    label?: string
    autoGenerated?: boolean
  }>(),
  {
    modelValue: false,
    label: '',
    autoGenerated: false,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const model = computed({
  get() {
    return props.modelValue ?? false
  },
  set(value: boolean) {
    emit('update:modelValue', value)
  },
})
</script>

<template>
  <div style="display:flex;align-items:center;gap:8px">
    <v-switch
      v-model="model"
      :label="label || (model ? 'True' : 'False')"
      inset
      hide-details
    />
    <span v-if="autoGenerated" class="auto-badge">Auto</span>
  </div>
</template>

<style scoped>
.auto-badge {
  font-size: 12px;
  padding: 4px 6px;
  border-radius: 4px;
  background: #eee;
  color: #333;
}
</style>
