<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    defaultValue?: string
    label?: string
    options?: Record<string, any> | null
    width?: string | null
    field: string
    required?: boolean
    modelValue?: string
    autoGenerated?: boolean
  }>(),
  {
    required: false,
    options: null,
    width: null,
    autoGenerated: false,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const fieldWidth = computed(() => (props.width === 'full' ? '100%' : '50%'))

const inputValue = computed({
  get() {
    return props.modelValue || props.defaultValue || ''
  },
  set(value: string) {
    emit('update:modelValue', value)
  },
})
</script>

<template>
  <div :style="`width: ${fieldWidth}; display:flex; align-items:center; gap:8px`">
    <v-text-field
      v-model="inputValue"
      :name="field"
      type="text"
      :label="label"
      :required="required"
      style="flex:1"
    />
    <span v-if="autoGenerated" class="auto-badge">Auto</span>
  </div>
</template>

<style scoped>
.auto-badge {
  font-size: 12px;
  padding: 4px 6px;
  border-radius: 4px;
  background: #eee;
  color: #333;
}

input {
  width: 100%;
}
</style>
