<template>
  <component
    v-if="field && field.meta && !field.meta.hidden"
    :key="field.field"
    :is="componentName"
    v-model="internalValue"
    :field="field.field"
    :width="field.meta?.width"
    :defaultValue="defaultValue"
    :label="label"
    :options="safeOptions"
    :required="required"
    :autoGenerated="internalAuto"
    :multiple="isMultiple"
    :collection="field.meta?.collection"
  />
  <span v-if="internalAuto" class="auto-badge">Auto‑generated</span>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useDirectusField } from '../composables/useDirectusField'

const props = defineProps<{ field: any; modelValue?: any }>()
const emit = defineEmits(['update:modelValue'])

// inject form context if parent provided it
const formContext = inject('directusForm', null)

const {
  internalValue,
  internalAuto,
  label,
  fieldLookup,
  required,
  safeOptions,
  defaultValue,
  isMultiple,
} = useDirectusField(props.field, props.modelValue, emit, formContext)

const componentName = computed(() => fieldLookup.value)
</script>
