import type {
  Mage_BundleProduct,
  Mage_ProductInterface
} from "../graphql/schema-types";
import type { Query as DirectusQuery } from 'adapter-directus';

// Union of possible codegen product models from your query
type RawMagentoProduct = Mage_BundleProduct | Mage_ProductInterface;

// Directus Products type fields aligned with meeovi-frontend graphql.ts
type DirectusProduct = {
  id: string
  sku?: string
  name?: string
  status?: string
  in_stock?: boolean
  price?: number
  description?: string | null
  short_description?: string | null
  image?: string | null
  gallery_images?: string[]
  dynamic_price?: boolean
  dynamic_sku?: boolean
}
type DirectusPage = {
  id: string
  name?: string
  slug?: string
  content?: string
  status?: string
  image?: string | null
  sort?: number
  type?: string
}

export function normalizeProductToPage(rawProduct: RawMagentoProduct): Partial<DirectusPage> {
  const isBundle = 'dynamic_price' in rawProduct;

  return {
    id: rawProduct.uid ?? rawProduct.id ?? '',
    name: rawProduct.name ?? '',
    slug: rawProduct.url_key ?? '',
    content: rawProduct.description?.html ?? '',
    status: rawProduct.status === 1 ? 'published' : 'draft',
    image: rawProduct.small_image?.url || rawProduct.image?.url || null,
    sort: 0,
    type: 'product_page'
  };
}

export function normalizeMagentoProduct(rawProduct: RawMagentoProduct): Partial<DirectusProduct> {
  // Discriminated union check for Bundle-specific properties
  const isBundle = 'dynamic_price' in rawProduct;
  const bundleProduct = isBundle ? (rawProduct as Mage_BundleProduct) : null;

  return {
    id: rawProduct.uid ?? rawProduct.id ?? '',
    sku: String(rawProduct.sku ?? ''),
    name: rawProduct.name ?? '',
    
    // Status mapping (Magento status 1 = enabled -> Directus 'published')
    status: rawProduct.status === 1 ? 'published' : 'draft',
    in_stock: rawProduct.stock_status === 'IN_STOCK',

    // Price range parsing
    price: rawProduct.price_range?.minimum_price?.final_price?.value ?? 0,

    // Extract html string from ComplexTextValue types generated by Codegen
    description: rawProduct.description?.html ?? null,
    short_description: rawProduct.short_description?.html ?? null,

    // Extract URL strings
    image: rawProduct.small_image?.url || rawProduct.image?.url || null,
    
    // Clean mapped array from media_gallery
    gallery_images: (rawProduct.media_gallery ?? [])
      .map((media) => media?.url)
      .filter((url): url is string => Boolean(url)),

    // Safely extract Bundle-only properties when __typename match is confirmed
    dynamic_price: isBundle ? (rawProduct as Mage_BundleProduct).dynamic_price ?? false : undefined,
    dynamic_sku: isBundle ? (rawProduct as Mage_BundleProduct).dynamic_sku ?? false : undefined,
  };
}