export interface SfAttribute {
  id: string;
  entityTypeId: string;
  attributeCode: string;
  backendModel?: string;
  backendType: "static" | "varchar" | "int" | "decimal" | "text" | "datetime" | "select" | "bool" | "json";
  backendTable?: string;
  frontendModel?: string;
  frontendInput: "text" | "textarea" | "date" | "boolean" | "multiselect" | "select" | "price" | "media_image" | "weee" | "swatch_visual" | "swatch_text";
  frontendLabel: string;
  frontendClass?: string;
  sourceModel?: string;
  isRequired: boolean;
  isUnique: boolean;
  isGlobal: boolean;
  isVisible: boolean;
  isSearchable: boolean;
  isFilterable: boolean;
  isComparable: boolean;
  isVisibleOnFront: boolean;
  usedInProductListing?: boolean;
  usedForSortBy?: boolean;
  isHtmlAllowedOnFront: boolean;
  isConfigurable: boolean;
  applyTo: SfProductType[];
  isVisibleInAdvancedSearch?: boolean;
  position: number;
  note: string;
  defaultValue: string | number | boolean | string[] | null;
  sortOrder?: number;
  extensionAttributes?: Record<string, unknown>;
}
