export interface SfCoupon {
  id: string;
  code: string;
  usageCount: number;
  usagePerCustomer: number;
  usageLimit: number;
  timesUsed: number;
  type: string;
  customerGroupIds: string[];
  isActive: boolean;
  isAutoGenerated: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface SfCartCoupon {
  id: string;
  couponId: string;
  code: string;
  ruleId: string;
  appliedAt: number;
  expirationDate?: string;
}
