export interface SfInvoice {
  id: string;
  incrementId: string;
  orderId: string;
  orderIncrementId: string;
  state: string;
  subTotal: number;
  baseSubTotal: number;
  subTotalInclTax: number;
  baseSubtotalInclTax: number;
  shippingAmount: number;
  baseShippingAmount: number;
  shippingDescription: string;
  shippingInclTax: number;
  baseShippingInclTax: number;
  shippingTaxAmount: number;
  baseShippingTaxAmount: number;
  discountAmount: number;
  baseDiscountAmount: number;
  discountDescription: string;
  grandTotal: number;
  baseGrandTotal: number;
  taxAmount: number;
  baseTaxAmount: number;
  discountTaxCompensationAmount: number;
  baseDiscountTaxCompensationAmount: number;
  shippingDiscountTaxCompensationAmount: number;
  baseShippingDiscountTaxCompensationAmount: number;
  subtotalInclTax: number;
  baseSubtotalInclTax: number;
  totalQty: number;
  emailSent: boolean;
  canVoid: boolean;
  canRefund: boolean;
  createdAt: string;
  updatedAt: string;
  extensionAttributes?: Record<string, unknown>;
}
