import type { SfProduct } from "./product";

export interface SfOrderItem {
  id: string;
  orderId: string;
  parentItemId?: string;
  productId: string;
  quoteItemId: string;
  sku: string;
  name: string;
  price: number;
  basePrice: number;
  rowTotal: number;
  baseRowTotal: number;
  qty: number;
  rowWeight: number;
  qtyCanceled: number;
  qtyInvoiced: number;
  qtyRefunded: number;
  qtyReturned: number;
  qtyShipped: number;
  discountAmount: number;
  baseDiscountAmount: number;
  taxAmount: number;
  baseTaxAmount: number;
  discountInvoiced: number;
  baseDiscountInvoiced: number;
  discountRefunded: number;
  baseDiscountRefunded: number;
  taxInvoiced: number;
  baseTaxInvoiced: number;
  taxRefunded: number;
  baseTaxRefunded: number;
  weeeTaxAppliedAmount: number;
  baseWeeeTaxAppliedAmount: number;
  createdAt: string;
  updatedAt: string;
  extensionAttributes?: Record<string, unknown>;
  // Additional links omitted
}

export interface SfOrder {
  id: string;
  incrementId: string;
  quoteId: string;
  state: string;
  status: string;
  customerId: string;
  customerFirstname?: string;
  customerLastname?: string;
  customerEmail: string;
  customerGroupId: number;
  customerIsGuest: boolean;
  customerNote?: string;
  customerNoteNotify: boolean;
  couponCode?: string;
  discountDescription?: string;
  totalQtyOrdered: number;
  totalQtyInvoiced: number;
  totalQtyRefunded: number;
  totalQtyReturned: number;
  totalQtyCanceled: number;
  totalQtyShipped: number;
  baseDiscountAmount: number;
  discountAmount: number;
  baseSubtotal: number;
  subtotal: number;
  baseTaxAmount: number;
  taxAmount: number;
  baseGrandTotal: number;
  grandTotal: number;
  baseTotalDue: number;
  totalDue: number;
  baseTotalPaid: number;
  totalPaid: number;
  baseTotalRefunded: number;
  totalRefunded: number;
  shippingAmount: number;
  baseShippingAmount: number;
  shippingDescription: string;
  shippingMethod: string;
  shippingName: string;
  shippingTaxAmount: number;
  baseShippingTaxAmount: number;
  weight: number;
  emailSent: boolean;
  canShipPartially: boolean;
  canShipPartiallyItem: boolean;
  createdAt: string;
  updatedAt: string;
  orderDate: string;
  extensionAttributes?: Record<string, unknown>;
}
