<template>
  <AlternateUIBooleanInput v-bind="$props" @update:model-value="emit('update:modelValue', $event)" />
</template>

<script setup lang="ts">


defineProps<{
  modelValue?: boolean
  label?: string
  autoGenerated?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()
</script>