<template>
  <AlternateUISelectInput v-bind="$props" @update:model-value="emit('update:modelValue', $event)" />
</template>

<script setup lang="ts">
import { SelectInput as AlternateUISelectInput } from 'alternate-ui/shared-ui/components'

defineProps<{
  defaultValue?: string
  label?: string
  options?: Record<string, any>
  width?: string | null
  field: string
  required?: boolean
  modelValue?: string
  autoGenerated?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()
</script>
